# =============================================================================
#
# MODULE      : {{filename}}
# PROJECT     : {{project_namespace}}
# DESCRIPTION :
#
# Copyright (c) {{copyright_year}}, {{copyright_owner}}.  All rights reserved.
# =============================================================================



source 'https://rubygems.org'
gemspec
